import smtplib
from email.message import EmailMessage

def email_error(logloc, task, errorstep):
    msg = EmailMessage()
    newline = '\n'
    msg.set_content(f'This is an automatic e-mail generated by {task}.'
                    f''
                    f'Errors were encountered during: {errorstep}.'
                    f'Please check the log file @ {logloc}'
                    f''
                    f'Kind regards,'
                    f'Clinical Genomics Gothenburg')

    msg['Subject'] = "ERROR: GENSAM upload"
    msg['From'] = "clinicalgenomics@gu.se"
    msg['To'] = "clinicalgenomics@gu.se"

    #Send the messege
    s = smtplib.SMTP('smtp.gu.se')
    s.send_message(msg)
    s.quit()

def email_micro(datatypes):
    msg = EmailMessage()
    msg.set_content(f'New data has been deliever to the KMIK sFTP outbox.'
                    f''
                    f'Kind regards,'
                    f'Clinical Genomics Gothenburg')

    msg['Subject'] = "Delivery of new COVIDseq data"
    msg['From'] = "clinicalgenomics@gu.se"
    msg['To'] = "johan.ringlander@vgregion.se"

    #Send the messege
    s = smtplib.SMTP('smtp.gu.se')
    s.send_message(msg)
    s.quit()
